import { createContext, useContext, useState, useEffect, useCallback } from 'react';

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', speechCode: 'en-IN' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', speechCode: 'hi-IN' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', speechCode: 'mr-IN' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', speechCode: 'bn-IN' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', speechCode: 'ta-IN' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', speechCode: 'te-IN' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', speechCode: 'gu-IN' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', speechCode: 'kn-IN' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', speechCode: 'ml-IN' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', speechCode: 'pa-IN' }
];

export const translations = {
  en: {
    govInitiative: 'Government of India Initiative',
    ministry: 'Government of India | Ministry of Consumer Affairs, Food & Public Distribution',
    portalTitle: 'TolSeva — Legal Metrology Department',
    portalSubtitle: 'Unified Online Verification & Certification Platform',
    helpline: 'Helpline',
    officeHours: 'Mon–Fri, 10AM–5PM',
    navHome: 'Home',
    navAbout: 'About Us',
    navServices: 'Services',
    navContact: 'Contact',
    login: 'Login',
    logout: 'Logout',
    dashboard: 'Dashboard',
    heroTitle: 'Unified Online Verification & Certification for',
    heroHighlight: 'Legal Metrology',
    heroSub: 'Simplifying instrument verification, renewal, and certification for businesses across India under the Legal Metrology Act, 2009.',
    goToDashboard: 'Go to Dashboard',
    learnMore: 'Learn More',
    registeredBusinesses: 'Registered Businesses',
    instrumentsVerified: 'Instruments Verified',
    citizensHelped: 'Citizens & Vendors Helped',
    certificatesIssued: 'Certificates Issued',
    ourServices: 'Our Services',
    servicesSub: 'End-to-end digital services for vendors, inspectors, and administrators',
    instrumentReg: 'Instrument Registration',
    instrumentRegDesc: 'Register all your weighing and measuring instruments online with instant GSTIN verification.',
    digitalVerify: 'Digital Verification',
    digitalVerifyDesc: 'Government inspectors conduct field visits and issue tamper-proof digital certificates with QR codes.',
    voiceAssist: 'Voice Assistance',
    voiceAssistDesc: 'The AI chatbot supports Indian languages and voice queries to guide vendors through every step.',
    contactDept: 'Contact Legal Metrology Department',
    tollFree: 'Toll-Free Helpline',
    email: 'Email',
    selectLanguage: 'Select Language',
    quickLinks: 'Quick Links',
    assistantTitle: 'TolSeva Assistant',
    assistantSub: 'Voice & Text Support'
  },
  hi: {
    govInitiative: 'भारत सरकार की एक पहल',
    ministry: 'भारत सरकार | उपभोक्ता मामले, खाद्य एवं सार्वजनिक वितरण मंत्रालय',
    portalTitle: 'तोलसेवा — विधिक मापविज्ञान विभाग',
    portalSubtitle: 'एकीकृत ऑनलाइन सत्यापन एवं प्रमाणन मंच',
    helpline: 'हेल्पलाइन',
    officeHours: 'सोम–शुक्र, प्रातः 10 से सायं 5 बजे',
    navHome: 'मुख्य पृष्ठ',
    navAbout: 'हमारे बारे में',
    navServices: 'सेवाएं',
    navContact: 'संपर्क करें',
    login: 'लॉग इन',
    logout: 'लॉग आउट',
    dashboard: 'डैशबोर्ड',
    heroTitle: 'विधिक मापविज्ञान के लिए एकीकृत ऑनलाइन',
    heroHighlight: 'सत्यापन एवं प्रमाणन',
    heroSub: 'विधिक मापविज्ञान अधिनियम, 2009 के तहत पूरे भारत में व्यवसायों हेतु उपकरण सत्यापन, नवीनीकरण व प्रमाणन को सरल बनाना।',
    goToDashboard: 'डैशबोर्ड पर जाएं',
    learnMore: 'और जानें',
    registeredBusinesses: 'पंजीकृत व्यवसाय',
    instrumentsVerified: 'सत्यापित उपकरण',
    citizensHelped: 'नागरिक व विक्रेता लाभान्वित',
    certificatesIssued: 'जारी प्रमाणपत्र',
    ourServices: 'हमारी सेवाएं',
    servicesSub: 'विक्रेताओं, निरीक्षकों एवं प्रशासकों हेतु संपूर्ण डिजिटल सेवाएं',
    instrumentReg: 'उपकरण पंजीकरण',
    instrumentRegDesc: 'त्वरित जीएसटी सत्यापन के साथ अपने सभी तोल और माप उपकरणों का ऑनलाइन पंजीकरण करें।',
    digitalVerify: 'डिजिटल सत्यापन',
    digitalVerifyDesc: 'सरकारी निरीक्षक भौतिक निरीक्षण कर क्यूआर कोड युक्त डिजिटल प्रमाणपत्र जारी करते हैं।',
    voiceAssist: 'आवाज सहायता',
    voiceAssistDesc: 'एआई वॉयस चैटबॉट भारतीय भाषाओं में आवाज सहायता प्रदान कर प्रत्येक चरण में मार्गदर्शन करता है।',
    contactDept: 'विधिक मापविज्ञान विभाग से संपर्क करें',
    tollFree: 'टोल-फ्री हेल्पलाइन',
    email: 'ईमेल',
    selectLanguage: 'भाषा चुनें',
    quickLinks: 'त्वरित लिंक',
    assistantTitle: 'तोलसेवा सहायक',
    assistantSub: 'आवाज व पाठ्य सहायता'
  },
  mr: {
    govInitiative: 'भारत सरकारचा उपक्रम',
    ministry: 'भारत सरकार | ग्राहक व्यवहार, अन्न आणि सार्वजनिक वितरण मंत्रालय',
    portalTitle: 'तोलसेवा — वैध मापनशास्त्र विभाग',
    portalSubtitle: 'एकीकृत ऑनलाइन पडताळणी आणि प्रमाणन व्यासपीठ',
    helpline: 'हेल्पलाइन',
    officeHours: 'सोम–शुक्र, सकाळी 10 ते संध्याकाळी 5',
    navHome: 'मुख्यपृष्ठ',
    navAbout: 'आमच्याबद्दल',
    navServices: 'सेवा',
    navContact: 'संपर्क',
    login: 'लॉगिन',
    logout: 'लॉगआउट',
    dashboard: 'डॅशबोर्ड',
    heroTitle: 'वैध मापनशास्त्रासाठी एकीकृत ऑनलाइन',
    heroHighlight: 'पडताळणी आणि प्रमाणन',
    heroSub: 'वैध मापनशास्त्र कायदा, 2009 अंतर्गत देशभरातील व्यवसायांसाठी वजन व मापे पडताळणी व नूतनीकरण सुलभ करणे.',
    goToDashboard: 'डॅशबोर्डवर जा',
    learnMore: 'अधिक माहिती',
    registeredBusinesses: 'नोंदणीकृत व्यवसाय',
    instrumentsVerified: 'पडताळणी केलेली उपकरणे',
    citizensHelped: 'नागरिक व विक्रेते मदत',
    certificatesIssued: 'जारी केलेले प्रमाणपत्र',
    ourServices: 'आमच्या सेवा',
    servicesSub: 'विक्रेते, निरीक्षक आणि प्रशासकांसाठी डिजिटल सेवा',
    instrumentReg: 'उपकरण नोंदणी',
    instrumentRegDesc: 'जीएसटी पडताळणीसह आपल्या सर्व वजन आणि मापन उपकरणांची ऑनलाइन नोंदणी करा.',
    digitalVerify: 'डिजिटल पडताळणी',
    digitalVerifyDesc: 'शासकीय निरीक्षक जागेवर तपासणी करून क्यूआर कोड प्रमाणपत्र जारी करतात.',
    voiceAssist: 'व्हॉइस सहाय्यक',
    voiceAssistDesc: 'भारतीय भाषांमध्ये व्हॉइस चॅटबॉट प्रत्येक पायरीवर विक्रेत्यांना मार्गदर्शन करतो.',
    contactDept: 'वैध मापनशास्त्र विभागाशी संपर्क साधा',
    tollFree: 'टोल-फ्री हेल्पलाइन',
    email: 'ईमेल',
    selectLanguage: 'भाषा निवडा',
    quickLinks: 'महत्त्वाचे दुवे',
    assistantTitle: 'तोलसेवा सहाय्यक',
    assistantSub: 'व्हॉइस आणि मजकूर समर्थन'
  },
  bn: {
    govInitiative: 'ভারত সরকারের উদ্যোগ',
    ministry: 'ভারত সরকার | ক্রেতা সুরক্ষা, খাদ্য ও গণবন্টন মন্ত্রক',
    portalTitle: 'তোলসেবা — লিগ্যাল মেট্রোলজি বিভাগ',
    portalSubtitle: 'একীকৃত অনলাইন যাচাইকরণ এবং শংসাপত্র প্ল্যাটফর্ম',
    helpline: 'হেল্পলাইন',
    officeHours: 'সোম–শুক্র, সকাল ১০টা থেকে বিকেল ৫টা',
    navHome: 'হোম',
    navAbout: 'আমাদের সম্পর্কে',
    navServices: 'পরিষেবাসমূহ',
    navContact: 'যোগাযোগ',
    login: 'লগইন',
    logout: 'লগআউট',
    dashboard: 'ড্যাশবোর্ড',
    heroTitle: 'লিগ্যাল মেট্রোলজির জন্য একীকৃত অনলাইন',
    heroHighlight: 'যাচাইকরণ ও শংসাপত্র',
    heroSub: 'লিগ্যাল মেট্রোলজি আইন, ২০০৯-এর অধীনে সমগ্র ভারতে ব্যবসার জন্য ওজন ও পরিমাপ যন্ত্র যাচাইকরণ সহজতর করা।',
    goToDashboard: 'ড্যাশবোর্ডে যান',
    learnMore: 'আরও জানুন',
    registeredBusinesses: 'নিবন্ধিত ব্যবসা',
    instrumentsVerified: 'যাচাইকৃত যন্ত্র',
    citizensHelped: 'সহায়তাপ্রাপ্ত নাগরিক ও বিক্রেতা',
    certificatesIssued: 'প্রদত্ত শংসাপত্র',
    ourServices: 'আমাদের পরিষেবা',
    servicesSub: 'বিক্রেতা, পরিদর্শক এবং প্রশাসকদের জন্য সম্পূর্ণ ডিজিটাল পরিষেবা',
    instrumentReg: 'যন্ত্র নিবন্ধন',
    instrumentRegDesc: 'তাত্ক্ষণিক জিএসটি যাচাইকরণের সাথে আপনার ওজন ও পরিমাপ যন্ত্র অনলাইনে নিবন্ধন করুন।',
    digitalVerify: 'ডিজিটাল যাচাইকরণ',
    digitalVerifyDesc: 'সরকারি পরিদর্শকরা সরেজমিনে পরিদর্শন করে কিউআর কোড শংসাপত্র প্রদান করেন।',
    voiceAssist: 'ভয়েস সহায়তা',
    voiceAssistDesc: 'এআই ভয়েস চ্যাটবট ভারতীয় ভাষায় ভয়েস ও পাঠ্য সহায়তা প্রদান করে।',
    contactDept: 'লিগ্যাল মেট্রোলজি বিভাগের সাথে যোগাযোগ করুন',
    tollFree: 'টোল-ফ্রি হেল্পলাইন',
    email: 'ইমেল',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    quickLinks: 'প্রয়োজনীয় লিঙ্ক',
    assistantTitle: 'তোলসেবা সহায়ক',
    assistantSub: 'ভয়েস ও টেক্সট সহায়তা'
  },
  ta: {
    govInitiative: 'இந்திய அரசு முயற்சி',
    ministry: 'இந்திய அரசு | நுகர்வோர் விவகாரங்கள், உணவு மற்றும் பொது விநியோக அமைச்சகம்',
    portalTitle: 'டோல்சேவா — சட்ட அளவியல் துறை',
    portalSubtitle: 'ஒருங்கிணைந்த ஆன்லைன் சரிபார்ப்பு மற்றும் சான்றிதழ் தளம்',
    helpline: 'உதவி எண்',
    officeHours: 'திங்கள்–வெள்ளி, காலை 10 முதல் மாலை 5 வரை',
    navHome: 'முகப்பு',
    navAbout: 'எங்களை பற்றி',
    navServices: 'சேவைகள்',
    navContact: 'தொடர்பு கொள்ள',
    login: 'உள்நுழைய',
    logout: 'வெளியேறு',
    dashboard: 'டாஷ்போர்டு',
    heroTitle: 'சட்ட அளவியலுக்கான ஒருங்கிணைந்த ஆன்லைன்',
    heroHighlight: 'சரிபார்ப்பு மற்றும் சான்றிதழ்',
    heroSub: 'சட்ட அளவியல் சட்டம், 2009-ன் கீழ் இந்தியா முழுவதிலும் உள்ள வணிகங்களுக்கான எடையிடும் கருவிகளை சரிபார்த்தல்.',
    goToDashboard: 'டாஷ்போர்டிற்குச் செல்லவும்',
    learnMore: 'மேலும் அறிய',
    registeredBusinesses: 'பதிவு செய்யப்பட்ட வணிகங்கள்',
    instrumentsVerified: 'சரிபார்க்கப்பட்ட கருவிகள்',
    citizensHelped: 'பயனடைந்த குடிமக்கள் & வணிகர்கள்',
    certificatesIssued: 'வழங்கப்பட்ட சான்றிதழ்கள்',
    ourServices: 'எங்கள் சேவைகள்',
    servicesSub: 'வணிகர்கள், ஆய்வாளர்கள் மற்றும் நிர்வாகிகளுக்கான முழுமையான டிஜிட்டல் சேவைகள்',
    instrumentReg: 'கருவி பதிவு',
    instrumentRegDesc: 'உடனடி ஜிஎஸ்டி சரிபார்ப்புடன் உங்கள் எடை மற்றும் அளவீட்டு கருவிகளை ஆன்லைனில் பதிவு செய்யுங்கள்.',
    digitalVerify: 'டிஜிட்டல் சரிபார்ப்பு',
    digitalVerifyDesc: 'அரசு ஆய்வாளர்கள் கள ஆய்வு நடத்தி க்யூஆர் குறியீடு சான்றிதழை வழங்குகிறார்கள்.',
    voiceAssist: 'குரல் உதவி',
    voiceAssistDesc: 'AI குரல் சாட்பாட் இந்திய மொழிகளில் வழிகாட்டுகிறது.',
    contactDept: 'சட்ட அளவியல் துறையைத் தொடர்பு கொள்ளவும்',
    tollFree: 'கட்டணமில்லா உதவி எண்',
    email: 'மின்னஞ்சல்',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    quickLinks: 'முக்கிய இணைப்புகள்',
    assistantTitle: 'டோல்சேவா உதவியாளர்',
    assistantSub: 'குரல் மற்றும் உரை ஆதரவு'
  },
  te: {
    govInitiative: 'భారత ప్రభుత్వ చొరవ',
    ministry: 'భారత ప్రభుత్వం | వినియోగదారుల వ్యవహారాలు, ఆహార మరియు ప్రజా పంపిణీ మంత్రిత్వ శాఖ',
    portalTitle: 'తోల్సేవ — లీగల్ మెట్రాలజీ విభాగం',
    portalSubtitle: 'సమీకృత ఆన్‌లైన్ ధృవీకరణ మరియు సర్టిఫికేషన్ వేదిక',
    helpline: 'హెల్ప్‌లైన్',
    officeHours: 'సోమ–శుక్ర, ఉదయం 10 నుండి సాయంత్రం 5 వరకు',
    navHome: 'హోమ్',
    navAbout: 'మా గురించి',
    navServices: 'సేవలు',
    navContact: 'సంప్రదించండి',
    login: 'లాగిన్',
    logout: 'లాగౌట్',
    dashboard: 'డాష్‌బోర్డ్',
    heroTitle: 'లీగల్ మెట్రాలజీ కోసం సమీకృత ఆన్‌లైన్',
    heroHighlight: 'ధృవీకరణ మరియు సర్టిఫికేషన్',
    heroSub: 'లీగల్ మెట్రాలజీ చట్టం, 2009 కింద భారతదేశం అంతటా వ్యాపారాల కొలతల సాధనాల తనిఖీని సులభతరం చేయడం.',
    goToDashboard: 'డాష్‌బోర్డ్‌కి వెళ్లండి',
    learnMore: 'మరింత తెలుసుకోండి',
    registeredBusinesses: 'నమోదైన వ్యాపారాలు',
    instrumentsVerified: 'ధృవీకరించబడిన పరికరాలు',
    citizensHelped: 'లబ్ధి పొందిన వ్యాపారులు & పౌరులు',
    certificatesIssued: 'జారీ చేసిన సర్టిఫికెట్లు',
    ourServices: 'మా సేవలు',
    servicesSub: 'వ్యాపారులు, ఇన్‌స్పెక్టర్లు మరియు నిర్వాహకుల కోసం డిజిటల్ సేవలు',
    instrumentReg: 'పరికరాల నమోదు',
    instrumentRegDesc: 'తక్షణ జీఎస్టీ ధృవీకరణతో మీ బరువు మరియు కొలత సాధనాలను ఆన్‌లైన్‌లో నమోదు చేయండి.',
    digitalVerify: 'డిజిటల్ ధృవీకరణ',
    digitalVerifyDesc: 'ప్రభుత్వ అధికారులు తనిఖీ చేసి క్యూఆర్ కోడ్ సర్టిఫికేట్ జారీ చేస్తారు.',
    voiceAssist: 'వాయిస్ సహాయం',
    voiceAssistDesc: 'AI వాయిస్ చాట్‌బాట్ భారతీయ భాషలలో సహాయాన్ని అందిస్తుంది.',
    contactDept: 'లీగల్ మెట్రాలజీ విభాగాన్ని సంప్రదించండి',
    tollFree: 'టోల్-ఫ్రీ హెల్ప్‌లైన్',
    email: 'ఇమెయిల్',
    selectLanguage: 'భాషను ఎంచుకోండి',
    quickLinks: 'త్వరిత లింకులు',
    assistantTitle: 'తోల్సేవ సహాయకుడు',
    assistantSub: 'వాయిస్ మరియు టెక్స్ట్ మద్దతు'
  },
  gu: {
    govInitiative: 'ભારત સરકારની પહેલ',
    ministry: 'ભારત સરકાર | ગ્રાહક બાબતો, ખાદ્ય અને જાહેર વિતરણ મંત્રાલય',
    portalTitle: 'તોલસેવા — લીગલ મેટ્રોલોજી વિભાગ',
    portalSubtitle: 'સંકલિત ઓનલાઇન ચકાસણી અને પ્રમાણપત્ર પ્લેટફોર્મ',
    helpline: 'હેલ્પલાઇન',
    officeHours: 'સોમ–શુક્ર, સવારે 10 થી સાંજે 5',
    navHome: 'મુખ્ય પૃષ્ઠ',
    navAbout: 'અમારા વિશે',
    navServices: 'સેવાઓ',
    navContact: 'સંપર્ક કરો',
    login: 'લૉગિન',
    logout: 'લૉગઆઉટ',
    dashboard: 'ડેશબોર્ડ',
    heroTitle: 'લીગલ મેટ્રોલોજી માટે સંકલિત ઓનલાઇન',
    heroHighlight: 'ચકાસણી અને પ્રમાણપત્ર',
    heroSub: 'લીગલ મેટ્રોલોજી એક્ટ, 2009 હેઠળ ભારતના વ્યવસાયો માટે વજન અને માપન સાધનોની ચકાસણી સરળ બનાવવી.',
    goToDashboard: 'ડેશબોર્ડ પર જાઓ',
    learnMore: 'વધુ જાણો',
    registeredBusinesses: 'નોંધાયેલા વ્યવસાયો',
    instrumentsVerified: 'ચકાસાયેલ સાધનો',
    citizensHelped: 'લાભાર્થી નાગરિકો અને વેપારીઓ',
    certificatesIssued: 'આપેલા પ્રમાણપત્રો',
    ourServices: 'અમારી સેવાઓ',
    servicesSub: 'વેપારીઓ, નિરીક્ષકો અને વહીવટકર્તાઓ માટે ડિજિટલ સેવાઓ',
    instrumentReg: 'સાધન નોંધણી',
    instrumentRegDesc: 'જીએસટી ચકાસણી સાથે તમારા વજન અને માપન સાધનોની ઓનલાઇન નોંધણી કરો.',
    digitalVerify: 'ડિજિટલ ચકાસણી',
    digitalVerifyDesc: 'સરકારી નિરીક્ષકો સ્થળ પર તપાસ કરી ક્યૂઆર કોડ પ્રમાણપત્ર આપે છે.',
    voiceAssist: 'વોઇસ સહાય',
    voiceAssistDesc: 'એઆઈ વોઇસ ચેટબોટ ભારતીય ભાષાઓમાં માર્ગદર્શન આપે છે.',
    contactDept: 'લીગલ મેટ્રોલોજી વિભાગનો સંપર્ક કરો',
    tollFree: 'ટોલ-ફ્રી હેલ્પલાઇન',
    email: 'ઇમેઇલ',
    selectLanguage: 'ભાષા પસંદ કરો',
    quickLinks: 'ઝડપી લિંક્સ',
    assistantTitle: 'તોલસેવા સહાયક',
    assistantSub: 'વોઇસ અને ટેક્સ્ટ સપોર્ટ'
  },
  kn: {
    govInitiative: 'ಭಾರತ ಸರ್ಕಾರದ ಉಪಕ್ರಮ',
    ministry: 'ಭಾರತ ಸರ್ಕಾರ | ಗ್ರಾಹಕ ವ್ಯವಹಾರಗಳು, ಆಹಾರ ಮತ್ತು ಸಾರ್ವಜನಿಕ ವಿತರಣಾ ಸಚಿವಾಲಯ',
    portalTitle: 'ತೋಲ್‌ಸೇವಾ — ಲೀಗಲ್ ಮೆಟ್ರಾಲಜಿ ಇಲಾಖೆ',
    portalSubtitle: 'ಏಕೀಕೃತ ಆನ್‌ಲೈನ್ ಪರಿಶೀಲನೆ ಮತ್ತು ಪ್ರಮಾಣೀಕರಣ ವೇದಿಕೆ',
    helpline: 'ಸಹಾಯವಾಣಿ',
    officeHours: 'ಸೋಮ–ಶುಕ್ರ, ಬೆಳಿಗ್ಗೆ 10 ರಿಂದ ಸಂಜೆ 5',
    navHome: 'ಮುಖಪುಟ',
    navAbout: 'ನಮ್ಮ ಬಗ್ಗೆ',
    navServices: 'ಸೇವೆಗಳು',
    navContact: 'ಸಂಪರ್ಕಿಸಿ',
    login: 'ಲಾಗಿನ್',
    logout: 'ಲಾಗ್‌ಔಟ್',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    heroTitle: 'ಲೀಗಲ್ ಮೆಟ್ರಾಲಜಿಗಾಗಿ ಏಕೀಕೃತ ಆನ್‌ಲೈನ್',
    heroHighlight: 'ಪರಿಶೀಲನೆ ಮತ್ತು ಪ್ರಮಾಣೀಕರಣ',
    heroSub: 'ಲೀಗಲ್ ಮೆಟ್ರಾಲಜಿ ಕಾಯ್ದೆ, 2009 ರ ಅಡಿಯಲ್ಲಿ ತೂಕ ಮತ್ತು ಅಳತೆ ಉಪಕರಣಗಳ ಪರಿಶೀಲನೆಯನ್ನು ಸರಳಗೊಳಿಸುವುದು.',
    goToDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ',
    learnMore: 'ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ',
    registeredBusinesses: 'ನೋಂದಾಯಿತ ವ್ಯಾಪಾರಗಳು',
    instrumentsVerified: 'ಪರಿಶೀಲಿಸಿದ ಉಪಕರಣಗಳು',
    citizensHelped: 'ನೆರವು ಪಡೆದ ವ್ಯಾಪಾರಿಗಳು & ನಾಗರಿಕರು',
    certificatesIssued: 'ನೀಡಲಾದ ಪ್ರಮಾಣಪತ್ರಗಳು',
    ourServices: 'ನಮ್ಮ ಸೇವೆಗಳು',
    servicesSub: 'ವ್ಯಾಪಾರಿಗಳು, ಪರಿವೀಕ್ಷಕರು ಮತ್ತು ಆಡಳಿತಗಾರರಿಗೆ ಡಿಜಿಟಲ್ ಸೇವೆಗಳು',
    instrumentReg: 'ಉಪಕರಣ ನೋಂದಣಿ',
    instrumentRegDesc: 'ಜಿಎಸ್‌ಟಿ ಪರಿಶೀಲನೆಯೊಂದಿಗೆ ನಿಮ್ಮ ಎಲ್ಲಾ ತೂಕ ಮತ್ತು ಅಳತೆ ಉಪಕರಣಗಳನ್ನು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ನೋಂದಾಯಿಸಿ.',
    digitalVerify: 'ಡಿಜಿಟಲ್ ಪರಿಶೀಲನೆ',
    digitalVerifyDesc: 'ಸರ್ಕಾರಿ ಅಧಿಕಾರಿಗಳು ಸ್ಥಳ ಪರಿಶೀಲನೆ ನಡೆಸಿ ಕ್ಯೂಆರ್ ಕೋಡ್ ಪ್ರಮಾಣಪತ್ರ ನೀಡುತ್ತಾರೆ.',
    voiceAssist: 'ಧ್ವನಿ ಸಹಾಯ',
    voiceAssistDesc: 'AI ಧ್ವನಿ ಚಾಟ್‌ಬಾಟ್ ಭಾರತೀಯ ಭಾಷೆಗಳಲ್ಲಿ ಮಾರ್ಗದರ್ಶನ ನೀಡುತ್ತದೆ.',
    contactDept: 'ಲೀಗಲ್ ಮೆಟ್ರಾಲಜಿ ಇಲಾಖೆಯನ್ನು ಸಂಪರ್ಕಿಸಿ',
    tollFree: 'ಟೋಲ್-ಫ್ರೀ ಸಹಾಯವಾಣಿ',
    email: 'ಇಮೇಲ್',
    selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    quickLinks: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
    assistantTitle: 'ತೋಲ್‌ಸೇವಾ ಸಹಾಯಕ',
    assistantSub: 'ಧ್ವನಿ ಮತ್ತು ಪಠ್ಯ ಬೆಂಬಲ'
  },
  ml: {
    govInitiative: 'ഭാരത സർക്കാർ സംരംഭം',
    ministry: 'ഭാരത സർക്കാർ | ഉപഭോക്തൃകാര്യ, ഭക്ഷ്യ, പൊതുവിതരണ മന്ത്രാലയം',
    portalTitle: 'തോൽസേവ — ലീഗൽ മെട്രോളജി വകുപ്പ്',
    portalSubtitle: 'ഏകീകൃത ഓൺലൈൻ പരിശോധനയും സർട്ടിഫിക്കേഷൻ പ്ലാറ്റ്‌ഫോമും',
    helpline: 'ഹെൽപ്പ്‌ലൈൻ',
    officeHours: 'തിങ്കൾ–വെള്ളി, രാവിലെ 10 മുതൽ വൈകിട്ട് 5 വരെ',
    navHome: 'ഹോം',
    navAbout: 'ഞങ്ങളെക്കുറിച്ച്',
    navServices: 'സേവനങ്ങൾ',
    navContact: 'ബന്ധപ്പെടുക',
    login: 'ലോഗിൻ',
    logout: 'ലോഗൗട്ട്',
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    heroTitle: 'ലീഗൽ മെട്രോളജിക്കായുള്ള ഏകീകൃത ഓൺലൈൻ',
    heroHighlight: 'പരിശോധനയും സർട്ടിഫിക്കേഷനും',
    heroSub: 'ലീഗൽ മെട്രോളജി ആക്ട്, 2009 പ്രകാരം അളവുതൂക്ക ഉപകരണങ്ങൾ പരിശോധിക്കുന്ന പ്രക്രിയ ലളിതമാക്കുന്നു.',
    goToDashboard: 'ഡാഷ്‌ബോർഡിലേക്ക് പോകുക',
    learnMore: 'കൂടുതലറിയുക',
    registeredBusinesses: 'രജിസ്റ്റർ ചെയ്ത ബിസിനസുകൾ',
    instrumentsVerified: 'പരിശോധിച്ച ഉപകരണങ്ങൾ',
    citizensHelped: 'സഹായം ലഭിച്ച വ്യാപാരികളും പൗരന്മാരും',
    certificatesIssued: 'നൽകിയ സർട്ടിഫിക്കറ്റുകൾ',
    ourServices: 'ഞങ്ങളുടെ സേവനങ്ങൾ',
    servicesSub: 'വ്യാപാരികൾ, ഇൻസ്പെക്ടർമാർ എന്നിവർക്കായി സമഗ്ര ഡിജിറ്റൽ സേവനങ്ങൾ',
    instrumentReg: 'ഉപകരണ രജിസ്ട്രേഷൻ',
    instrumentRegDesc: 'ജിഎസ്ടി പരിശോധനയോടെ നിങ്ങളുടെ അളവുതൂക്ക ഉപകരണങ്ങൾ ഓൺലൈനായി രജിസ്റ്റർ ചെയ്യുക.',
    digitalVerify: 'ഡിജിറ്റൽ പരിശോധന',
    digitalVerifyDesc: 'സർക്കാർ ഇൻസ്പെക്ടർമാർ പരിശോധിച്ച് ക്യുആർ കോഡ് സർട്ടിഫിക്കറ്റ് നൽകുന്നു.',
    voiceAssist: 'ശബ്ദ സഹായം',
    voiceAssistDesc: 'AI വോയ്‌സ് ചാറ്റ്‌ബോട്ട് ഇന്ത്യൻ ഭാഷകളിൽ സഹായിക്കുന്നു.',
    contactDept: 'ലീഗൽ മെട്രോളജി വകുപ്പുമായി ബന്ധപ്പെടുക',
    tollFree: 'ടോൾ ഫ്രീ ഹെൽപ്പ്‌ലൈൻ',
    email: 'ഇമെയിൽ',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    quickLinks: 'പ്രധാന ലിങ്കുകൾ',
    assistantTitle: 'തോൽസേവ സഹായി',
    assistantSub: 'ശബ്ദ, വാചക പിന്തുണ'
  },
  pa: {
    govInitiative: 'ਭਾਰਤ ਸਰਕਾਰ ਦੀ ਪਹਿਲਕਦਮੀ',
    ministry: 'ਭਾਰਤ ਸਰਕਾਰ | ਖਪਤਕਾਰ ਮਾਮਲੇ, ਖੁਰਾਕ ਅਤੇ ਜਨਤਕ ਵੰਡ ਮੰਤਰਾਲਾ',
    portalTitle: 'ਤੋਲਸੇਵਾ — ਲੀਗਲ ਮੈਟ੍ਰੋਲੋਜੀ ਵਿਭਾਗ',
    portalSubtitle: 'ਏਕੀਕ੍ਰਿਤ ਆਨਲਾਈਨ ਤਸਦੀਕ ਅਤੇ ਸਰਟੀਫਿਕੇਸ਼ਨ ਪਲੇਟਫਾਰਮ',
    helpline: 'ਹੈਲਪਲਾਈਨ',
    officeHours: 'ਸੋਮ–ਸ਼ੁੱਕਰ, ਸਵੇਰੇ 10 ਤੋਂ ਸ਼ਾਮ 5 ਵਜੇ',
    navHome: 'ਮੁੱਖ ਪੰਨਾ',
    navAbout: 'ਸਾਡੇ ਬਾਰੇ',
    navServices: 'ਸੇਵਾਵਾਂ',
    navContact: 'ਸੰਪਰਕ ਕਰੋ',
    login: 'ਲਾਗਇਨ',
    logout: 'ਲਾਗਆਉਟ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    heroTitle: 'ਲੀਗਲ ਮੈਟ੍ਰੋਲੋਜੀ ਲਈ ਏਕੀਕ੍ਰਿਤ ਆਨਲਾਈਨ',
    heroHighlight: 'ਤਸਦੀਕ ਅਤੇ ਸਰਟੀਫਿਕੇਸ਼ਨ',
    heroSub: 'ਲੀਗਲ ਮੈਟ੍ਰੋਲੋਜੀ ਐਕਟ, 2009 ਦੇ ਤਹਿਤ ਕਾਰੋਬਾਰਾਂ ਲਈ ਮਾਪਣ ਵਾਲੇ ਯੰਤਰਾਂ ਦੀ ਤਸਦੀਕ ਨੂੰ ਆਸਾਨ ਬਣਾਉਣਾ।',
    goToDashboard: 'ਡੈਸ਼ਬੋਰਡ ਤੇ ਜਾਓ',
    learnMore: 'ਹੋਰ ਜਾਣੋ',
    registeredBusinesses: 'ਰਜਿਸਟਰਡ ਕਾਰੋਬਾਰ',
    instrumentsVerified: 'ਤਸਦੀਕਸ਼ੁਦਾ ਯੰਤਰ',
    citizensHelped: 'ਲਾਭਪਾਤਰੀ ਵਪਾਰੀ ਅਤੇ ਨਾਗਰਿਕ',
    certificatesIssued: 'ਜਾਰੀ ਕੀਤੇ ਸਰਟੀਫਿਕੇਟ',
    ourServices: 'ਸਾਡੀਆਂ ਸੇਵਾਵਾਂ',
    servicesSub: 'ਵਪਾਰੀਆਂ, ਇੰਸਪੈਕਟਰਾਂ ਅਤੇ ਪ੍ਰਸ਼ਾਸਕਾਂ ਲਈ ਡਿਜੀਟਲ ਸੇਵਾਵਾਂ',
    instrumentReg: 'ਯੰਤਰ ਰਜਿਸਟ੍ਰੇਸ਼ਨ',
    instrumentRegDesc: 'ਜੀਐਸਟੀ ਤਸਦੀਕ ਨਾਲ ਆਪਣੇ ਤੋਲ ਅਤੇ ਮਾਪਣ ਵਾਲੇ ਯੰਤਰਾਂ ਨੂੰ ਆਨਲਾਈਨ ਰਜਿਸਟਰ ਕਰੋ।',
    digitalVerify: 'ਡਿਜੀਟਲ ਤਸਦੀਕ',
    digitalVerifyDesc: 'ਸਰਕਾਰੀ ਇੰਸਪੈਕਟਰ ਨਿਰੀਖਣ ਕਰਕੇ ਕਿਊਆਰ ਕੋਡ ਸਰਟੀਫਿਕੇਟ ਜਾਰੀ ਕਰਦੇ ਹਨ।',
    voiceAssist: 'ਆਵਾਜ਼ ਸਹਾਇਤਾ',
    voiceAssistDesc: 'AI ਵੌਇਸ ਚੈਟਬੌਟ ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਸਹਾਇਤਾ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ।',
    contactDept: 'ਲੀਗਲ ਮੈਟ੍ਰੋਲੋਜੀ ਵਿਭਾਗ ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
    tollFree: 'ਟੋਲ-ਫ੍ਰੀ ਹੈਲਪਲਾਈਨ',
    email: 'ਈਮੇਲ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    quickLinks: 'ਜ਼ਰੂਰੀ ਲਿੰਕ',
    assistantTitle: 'ਤੋਲਸੇਵਾ ਸਹਾਇਕ',
    assistantSub: 'ਆਵਾਜ਼ ਅਤੇ ਟੈਕਸਟ ਸਹਾਇਤਾ'
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('tolseva_lang') || 'en';
  });

  const changeLanguage = useCallback((newCode) => {
    if (SUPPORTED_LANGUAGES.some(l => l.code === newCode)) {
      setLanguage(newCode);
      localStorage.setItem('tolseva_lang', newCode);
    }
  }, []);

  const t = useCallback((key) => {
    const langSet = translations[language] || translations.en;
    return langSet[key] || translations.en[key] || key;
  }, [language]);

  const currentLangObj = SUPPORTED_LANGUAGES.find(l => l.code === language) || SUPPORTED_LANGUAGES[0];

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, currentLangObj, languages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
